<!DOCTYPE html>
<html>
<head>
	<title>formularios </title>
</head>
<body>
<h1>SELECCIONE RANGO PARA CALCULAR </h1>

</table>
<p> SELECCIONE UN OPCION PARA CALCULAR:</p>
<SELECT NAME="OPCION">
	
$n1=0;
$n2=1;


<OPTION VALUE> "SELECCIONE UNA OPCION"</OPTION>
<OPTION VALUE>"FIBONACCI"</OPTION>
<OPTION VALUE>"CUADRADO"</OPTION>
<OPTION VALUE>"CUBO" </OPTION>
<FORM ACTION="COMPROBAR.PHP" METHOD="POST"/>

<P>NUMEROS: <INPUT TYPE="TEXT" </p>
<P><INPUT TYPE="SUBMIT" VALUE="COMPROBAR"> </INPUT>





</body>
</html>